---
- hosts: all
  become: true
  vars:
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
    - name: docker
  roles:
  - {role: postgres-install}
  - {role: guacd-install}
  - {role: guacamole-install}
