---
- name: run metricbeat dashboard setup against elasticsearch
  command: "docker exec metricbeat metricbeat setup --template -E output.logstash.enabled=false -E output.elasticsearch.username=\"{{ elasticsearch_username }}\" -E output.elasticsearch.password=\"{{ elasticsearch_password }}\" -E 'output.elasticsearch.hosts=[\"{{ elasticsearch_server }}\"]'"
  become: true
- name: run packetbeat dashboard setup against elasticsearch
  command: "docker exec packetbeat packetbeat setup --template -E output.logstash.enabled=false -E output.elasticsearch.username=\"{{ elasticsearch_username }}\" -E output.elasticsearch.password=\"{{ elasticsearch_password }}\" -E 'output.elasticsearch.hosts=[\"{{ elasticsearch_server }}\"]'"
  become: true
- name: run auditbeat dashboard setup against elasticsearch
  command: "docker exec auditbeat auditbeat setup --template -E output.logstash.enabled=false -E output.elasticsearch.username=\"{{ elasticsearch_username }}\" -E output.elasticsearch.password=\"{{ elasticsearch_password }}\" -E 'output.elasticsearch.hosts=[\"{{ elasticsearch_server }}\"]'"
  become: true
- name: run filebeat dashboard setup against elasticsearch
  command: "docker exec filebeat filebeat setup --template -E output.logstash.enabled=false -E output.elasticsearch.username=\"{{ elasticsearch_username }}\" -E output.elasticsearch.password=\"{{ elasticsearch_password }}\" -E 'output.elasticsearch.hosts=[\"{{ elasticsearch_server }}\"]'"
  become: true
