---
- hosts: all
  become: true
  vars:
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
    - name: docker
    - name: docker-compose
  roles:
  - { role: geerlingguy.pip }
  - { role: geerlingguy.docker }
  - { role: sniper }
