---
- hosts: all
  tasks:
  - name: disable account creation in env file
    replace:
      path: /opt/mozdef/meteor/imports/settings.js
      regexp: 'enableClientAccountCreation: allowAccountCreation,'
      replace: '// enableClientAccountCreation: allowAccountCreation,'
    become: true
  - name: docker-compose build /opt/mozdef/docker/compose
    shell: "docker-compose build --build-arg ENV_FILE=/opt/mozdef/docker/compose/mozdef.env"
    args:
      chdir: /opt/mozdef/docker/compose
    become: true
  - name: restart mozdef.service
    systemd:
      name: mozdef
      enabled: true
      state: restarted
    become: true
