---
- hosts: all
  tasks:
  - name: docker-compose build /opt/mozdef/docker/compose
    shell: "docker-compose build --build-arg OPTIONS_METEOR_PORT={{ http_port }} --build-arg OPTIONS_METEOR_KIBANAURL={{ mozdef_uri }}:9090/app/kibana --build-arg OPTIONS_METEOR_ROOTURL=http://{{ mozdef_uri }} --build-arg OPTIONS_METEOR_ENABLECLIENTACCOUNTCREATION=false"
    args:
      chdir: /opt/mozdef/docker/compose
    become: true
  - name: restart mozdef.service
    systemd:
      name: mozdef
      enabled: true
      state: restarted
    become: true
