---
- include_tasks: windows.yml
  when: ansible_facts['os_family'] == 'Windows'
- include_tasks: darwin.yml
  when: ansible_facts['os_family'] == 'Darwin'
- include_tasks: linux.yml
  when: ansible_facts['os_family'] != 'Windows' and ansible_facts['os_family'] != 'Darwin'
