---
- name: create wordpress directory
  file:
    path: "/opt/{{ wordpress_name }}"
    state: directory
  become: true
- name: install wordpress docker
  docker_container:
    name: "{{ wordpress_name }}"
    image: wordpress
    state: started
    restart_policy: unless-stopped
    #log_driver: json
    #    log_options:
    #        syslog-address: udp://testhost:5044
    #  syslog-facility: daemon
    #  tag: wordpress
    links:
    - "{{ mysql_name }}:mysql"
    ports:
    - "{{ wordpress_port }}:80"
    env:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "{{ mysql_db }}"
      WORDPRESS_DB_USER: "{{ mysql_user }}"
      WORDPRESS_DB_PASSWORD: "{{ mysql_password }}" 
    volumes:
    - "/opt/{{ wordpress_name }}/root_html:/var/www/html"
  become: true
