---
- name: pull elasticsearch docker image
  docker_image:
    name: elasticsearch
    source: pull
    tag: "{{ elk_version_tag }}"
  become: true
- name: create elk_elasticsearch_data docker volume
  docker_volume:
    name: elk_elasticsearch_data
  become: true
- name: increase max memory for elasticsearch
  shell: sysctl -w vm.max_map_count=262144
  become: true
- name: run elasticsearch docker container
  docker_container:
    name: elk_elasticsearch
    image: "elasticsearch:{{ elk_version_tag }}"
    state: started
    restart_policy: unless-stopped
    volumes:
    - elk_elasticsearch_data:/usr/share/elasticsearch/data
    env:
      http.host: "0.0.0.0"
      transport.host: "0.0.0.0"
      xpack.security.enabled: "false"
      cluster.name: "elk"
      discovery.type: "single-node"
    ulimits:
    - nofile:65536:65536
  become: true
