Vagrant.configure("2") do |config|
  config.vm.define "elk-stack" do |subconfig|
    subconfig.vm.box = "generic/ubuntu1904"
    subconfig.vm.hostname = "elk"
    subconfig.vm.network :private_network, ip: "10.10.5.5"
    subconfig.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end
  
  config.vm.provision "file", source: "files/logstash", destination: "/tmp/logstash/conf"
 
  config.vm.provision "shell", path: "scripts/setup.sh"
end
