---
- name: create graylog system user
  user:
    name: graylog-docker
    comment: 'graylog docker system user'
    system: true
    uid: 2150
  become: true
- name: pull mongo docker image
  docker_image:
    name: mongo
    tag: 3
  become: true
- name: pull elasticsearch docker image
  docker_image:
    name: docker.elastic.co/elasticsearch/elasticsearch
    tag: "{{ es_docker_tag }}"
  become: true
- name: pull graylog docker image
  docker_image:
    name: graylog/graylog
    tag: "{{ graylog_docker_tag }}"
  become: true
- name: create elasticsearch volume
  docker_volume:
    name: elasticsearch_data
  become: true
- name: create graylog_data volume
  docker_volume:
    name: graylog_data
  become: true
- name: create graylog_journal volume
  docker_volume:
    name: graylog_journal
  become: true
- name: run mongo docker container
  docker_container:
    name: mongo
    image: mongo:3
    state: started
    restart_policy: unless-stopped
    user: 2150
    ports:
    - 27017:27017
    volumes:
    - /opt/graylog-docker/mongo_data:/data/db
  become: true
- name: increase max memory for elasticsearch
  shell: sysctl -w vm.max_map_count=262144
  become: true
- name: run elasticsearch docker container
  docker_container:
    name: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:{{ es_docker_tag }}"
    state: started
    restart_policy: unless-stopped
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data
    env:
      http.host: "0.0.0.0"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "{{ es_java_opts }}"
    user: 2150
  become: true
- name: run graylog docker container
  docker_container:
    name: graylog
    image: "graylog/graylog:{{ graylog_docker_tag }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
    - graylog_journal:/usr/share/graylog/data/journal
    - graylog_data:/usr/share/graylog/data/
    env:
      GRAYLOG_PASSWORD_SECRET: "{{ graylog_password_secret }}"
      GRAYLOG_ROOT_USERNAME: "{{ graylog_root_username }}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "{{ graylog_root_password_sha2 }}"
      GRAYLOG_HTTP_EXTERNAL_URI: "{{ graylog_http_external_uri }}"
      GRAYLOG_HTTP_PUBLISH_URI: "{{ graylog_http_publish_uri }}"
      GRAYLOG_MONGODB_URI: "{{ graylog_mongodb_uri }}"
      GRAYLOG_ELASTICSEARCH_HOSTS: "{{ graylog_elasticsearch_hosts }}"
  become: true
