---
- name: create graylog system user
  user:
    name: graylog-docker
    comment: 'graylog docker system user'
    system: true
    uid: 2150
  become: true
- name: pull mongo docker image
  docker_image:
    name: mongo
    tag: 3
  become: true
- name: pull elasticsearch docker image
  docker_image:
    name: docker.elastic.co/elasticsearch/elasticsearch
    tag: "{{ es_docker_tag }}"
  become: true
- name: pull graylog docker image
  docker_image:
    name: graylog/graylog
    tag: "{{ graylog_docker_tag }}"
  become: true
- name: Create mongo volume
  docker_volume:
    name: mongo_data
  become: true
- name: Create elasticsearch volume
  docker_volume:
    name: elasticsearch_data
  become: true
- name: Create graylog journal volume
  docker_volume:
    name: graylog_journal
  become: true
- name: run mongo docker container
  docker_container:
    name: mongo
    image: mongo:3
    state: started
    restart_policy: unless-stopped
    ports:
    - 27017:27017
    volumes:
    - mongo_data:/data/db
    user: 2150
  become: true
- name: run elasticsearch docker container
  docker_container:
    name: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:{{ es_docker_tag }}"
    state: started
    restart_policy: unless-stopped
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data
    env:
      http.host: "127.0.0.1"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "{{ es_java_opts }}"
    user: 2150
  become: true
- name: run graylog docker container
  docker_container:
    name: graylog
    image: "graylog/graylog:{{ graylog_docker_tag }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
    - graylog_journal:/usr/share/graylog/data/journal
    env:
      GRAYLOG_PASSWORD_SECRET: "{{ graylog_password_secret }}"
      GRAYLOG_ROOT_USERNAME: "{{ graylog_root_username }}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "{{ graylog_root_password_sha2 }}"
      GRAYLOG_HTTP_EXTERNAL_URI: "{{ graylog_http_external_uri }}"
      GRAYLOG_HTTP_PUBLISH_URI: "{{ graylog_http_publish_uri }}"
    user: 2150
  become: true
- name: enable ufw, allow access to mongodb from localhost 
  ufw:
    state: enabled
    rule: allow
    src: 127.0.0.1
    port: 27017
  become: true
- name: deny access to mongodb from anywhere 
  ufw:
    rule: deny
    port: 27017
  become: true
- name: allow access to elasticsearch from localhost
  ufw:
    rule: allow
    src: 127.0.0.1
    port: 9200
  become: true
- name: allow access to elasticsearch from localhost
  ufw:
    rule: allow
    src: 127.0.0.1
    port: 9300
  become: true
- name: deny access to elasticsearch from anywhere 
  ufw:
    rule: deny
    port: 9200
  become: true
- name: deny access to elasticsearch from anywhere 
  ufw:
    rule: deny
    port: 9300
  become: true
