---
- name: create graylog system user
  user:
    name: graylog-docker
    comment: 'graylog docker system user'
    system: true
    uid: 2150
  become: true
- name: pull mongo docker image
  docker_image:
    name: mongo
    tag: 3
  become: true
- name: pull elasticsearch docker image
  docker_image:
    name: docker.elastic.co/elasticsearch/elasticsearch
    tag: "{{ es_docker_tag }}"
  become: true
- name: pull graylog docker image
  docker_image:
    name: graylog/graylog
    tag: "{{ graylog_docker_tag }}"
  become: true
- name: create mongo volume in /opt/graylog-docker/mongo_data
  file:
    path: /opt/graylog-docker/mongo_data
    state: directory
    owner: graylog-docker
    mode: 0700
  become: true
- name: create graylog_journal volume in /opt/graylog-docker/graylog_journal
  file:
    path: /opt/graylog-docker/graylog_journal
    state: directory
    owner: graylog-docker
    mode: 0700
  become: true
- name: copy 
- name: create graylog_data volume in /opt/graylog-docker/graylog_data
  file:
    path: /opt/graylog-docker/graylog_data/config
    state: directory
    owner: graylog-docker
    mode: 0700
  become: true
- name: place graylog.conf in /opt/graylog-docker/graylog_data/config
  copy:
    src: graylog.conf
    dest: /opt/graylog-docker/graylog_data/config/graylog.conf
    owner: graylog-docker
    mode: 0600
  become: true
- name: replace http_external_uri in /opt/graylog-docker/graylog_data/config/graylog.conf
  replace:
    path: /opt/graylog-docker/graylog_data/config/graylog.conf
    regexp: '#http_external_uri ='
    replace: "http_external_uri = {{ graylog_http_external_uri }}"
  become: true
- name: replace http_publish_uri in /opt/graylog-docker/graylog_data/config/graylog.conf
  replace:
    path: /opt/graylog-docker/graylog_data/config/graylog.conf
    regexp: '#http_publish_uri = http://192.168.1.1:9000/'
    replace: "http_publish_uri = {{ graylog_http_publish_uri }}"
  become: true
- name: replace root_password_sha2 in /opt/graylog-docker/graylog_data/config/graylog.conf
  replace:
    path: /opt/graylog-docker/graylog_data/config/graylog.conf
    regexp: 'root_password_sha2 ='
    replace: "root_password_sha2 = {{ graylog_root_password_sha2 }}"
  become: true
- name: replace root_username in /opt/graylog-docker/graylog_data/config/graylog.conf
  replace:
    path: /opt/graylog-docker/graylog_data/config/graylog.conf
    regexp: '#root_username = admin'
    replace: "root_username = {{ graylog_root_username }}"
  become: true
- name: replace password_secret in /opt/graylog-docker/graylog_data/config/graylog.conf
  replace:
    path: /opt/graylog-docker/graylog_data/config/graylog.conf
    regexp: '#http_external_uri ='
    replace: "http_external_uri = {{ graylog_http_external_uri }}"
  become: true
- name: replace password_secret in /opt/graylog-docker/graylog_data/config/graylog.conf
  replace:
    path: /opt/graylog-docker/graylog_data/config/graylog.conf
    regexp: 'password_secret ='
    replace: "password_secret = = {{ graylog_password_secret }}"
  become: true
- name: place log4j2.xml in /opt/graylog-docker/graylog_data/config
  copy:
    src: log4j2.xml
    dest: /opt/graylog-docker/graylog_data/config/log4j2.xml
    owner: graylog-docker
    mode: 0600
  become: true
- name: create elasticsearch volume
  docker_volume:
    name: elasticsearch_data
  become: true
- name: run mongo docker container
  docker_container:
    name: mongo
    image: mongo:3
    state: started
    restart_policy: unless-stopped
    user: 2150
    ports:
    - 27017:27017
    volumes:
    - /opt/graylog-docker/mongo_data:/data/db
  become: true
- name: increase max memory for elasticsearch
  shell: sysctl -w vm.max_map_count=262144
  become: true
- name: run elasticsearch docker container
  docker_container:
    name: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:{{ es_docker_tag }}"
    state: started
    restart_policy: unless-stopped
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data
    env:
      http.host: "0.0.0.0"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "{{ es_java_opts }}"
    user: 2150
  become: true
- name: run graylog docker container
  docker_container:
    name: graylog
    image: "graylog/graylog:{{ graylog_docker_tag }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
    - /opt/graylog-docker/graylog_journal:/usr/share/graylog/data/journal
    - /opt/graylog-docker/graylog_data:/usr/share/graylog/data/
    env:
      GRAYLOG_PASSWORD_SECRET: "{{ graylog_password_secret }}"
      GRAYLOG_ROOT_USERNAME: "{{ graylog_root_username }}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "{{ graylog_root_password_sha2 }}"
      GRAYLOG_HTTP_EXTERNAL_URI: "{{ graylog_http_external_uri }}"
      GRAYLOG_HTTP_PUBLISH_URI: "{{ graylog_http_publish_uri }}"
    user: 2150
  become: true
- name: enable ufw, allow access to mongodb from localhost 
  ufw:
    state: enabled
    rule: allow
    src: 127.0.0.1
    port: 27017
  become: true
- name: deny access to mongodb from anywhere 
  ufw:
    rule: deny
    port: 27017
  become: true
- name: allow access to elasticsearch from localhost
  ufw:
    rule: allow
    src: 127.0.0.1
    port: 9200
  become: true
- name: allow access to elasticsearch from localhost
  ufw:
    rule: allow
    src: 127.0.0.1
    port: 9300
  become: true
- name: deny access to elasticsearch from anywhere 
  ufw:
    rule: deny
    port: 9200
  become: true
- name: deny access to elasticsearch from anywhere 
  ufw:
    rule: deny
    port: 9300
  become: true
