---
- name: pull elastalert docker image
  docker_image:
    name: bitsensor/elastalert
    source: pull
    tag: "{{ elastalert_tag }}"
  become: true
- name: create /opt/elastalert/ directory
  file:
    path: /opt/elastalert/
    state: directory
    owner: root
    mode: 0700
  become: true
- name: copy elastalert files to /opt/elastalert
  copy:
    src: elastalert/
    dest: /opt/elastalert
  become: true
- name: add elasticsearch username and password to elastalert config
  replace:
    path: /opt/elastalert/config/elastalert.yaml
    regexp: '#es_username: someusername'
    replace: "es_username: {{ es_username }}"
  become: true
- name: add elasticsearch username and password to elastalert config
  replace:
    path: /opt/elastalert/config/elastalert.yaml
    regexp: '#es_password: somepassword'
    replace: "es_password: {{ es_password }}"
  become: true
- name: add webhook url
  replace:
    path: "{ item }"
    regexp: 'slack_webhook_url: [slack_webhook]'
    replace: "slack_webhook_url: {{ slack_webhook }}"
  with_items:
  - /opt/elastalert/rules/ssh_login_failures.yaml
  - /opt/elastalert/rules/sudo_authentication_failure.yaml 
  - /opt/elastalert/rules/sudo_user_not_in_sudoers.yaml
  become: true
- name: run elastalert docker container
  docker_container:
    name: elastalert
    image: "bitsensor/elastalert:{{ elastalert_tag }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
    - /opt/elastalert/config/elastalert.yaml:/opt/elastalert/config.yaml
    - /opt/elastalert/config/elastalert-test.yaml:/opt/elastalert/config-test.yaml
    - /opt/elastalert/config/config.json:/opt/elastalert-server/config/config.json
    - /opt/elastalert/rules:/opt/elastalert/rules
    - /opt/elastalert/rule_templates:/opt/elastalert/rule_templates
  become: true
