---
- name: add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'
- name: "add docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_distribution }} stable"
    state: present
    filename: docker
  become: true
  when: ansible_distribution == 'Ubuntu'
- name: install misc packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - "aptitude"
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"
  become: true
  when: ansible_distribution == 'Ubuntu'
- name: install docker-ce
  apt:
    name: "docker-ce"
    update_cache: yes
  become: true
  when: ansible_distribution == 'Ubuntu'
- name: add python docker package
  pip:
    name:
    - docker-py
  become: true
  retries: 5
- name: enable and start docker
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true
  retries: 5
