---
- name: copy iptables-restore service
  copy:
    src: iptables-restore.service
    dest: /etc/systemd/system/iptables-restore.service
    mode: 0600
  become: true
- name: copy iptables-restore.sh script
  copy:
    src: iptables-restore.sh
    dest: /opt/iptables-restore.sh
    mode: 0700
  become: true
- name: enable iptables-restore service
  systemd:
    name: iptables-restore
    enabled: yes
  become: true
- name: allow mongo from localhost
  iptables:
    chain: INPUT
    protocol: tcp
    source: 127.0.0.1
    jump: ACCEPT
    to_port: 27017
  become: true
- name: allow elasticsearch from localhost
  iptables:
    chain: INPUT
    protocol: tcp
    source: 127.0.0.1
    jump: ACCEPT
    to_port: 9200
  become: true
- name: allow elasticsearch from localhost
  iptables:
    chain: INPUT
    protocol: tcp
    source: 127.0.0.1
    jump: ACCEPT
    to_port: 9300
  become: true
- name: deny mongo from anywhere
  iptables:
    chain: INPUT
    protocol: tcp
    jump: DROP
    to_port: 27017
  become: true
- name: deny elasticsearch from anywhere
  iptables:
    chain: INPUT
    protocol: tcp
    jump: DROP
    to_port: 9200
  become: true
- name: deny elasticsearch from anywhere
  iptables:
    chain: INPUT
    protocol: tcp
    jump: DROP
    to_port: 9300
  become: true
- name: save to iptables.rules
  shell: /sbin/iptables-save > /etc/iptables.rules
  become: true
