---
- name: install winlogbeat
  win_chocolatey:
    name: winlogbeat
    version: "{{ beats_version_tag }}"
  become: true
- name: copy winlogbeat.yml to 'C:\ProgramData\chocolatey\lib\winlogbeat\tools\winlogbeat.yml'
  win_copy:
    src: winlogbeat.yml
    dest: "C:\\ProgramData\\chocolatey\\lib\\winlogbeat\\tools\\winlogbeat.yml"
    backup: yes
  become: true
- name: replace logstash host config in 'C:\ProgramData\chocolatey\lib\winlogbeat\tools\winlogbeat.yml'
  win_lineinfile:
    path: "C:\\ProgramData\\chocolatey\\lib\\winlogbeat\\tools\\winlogbeat.yml"
    regexp: 'hosts: \["mylogstash_host:5044"\]'
    line: '  hosts: ["{{ beats_server }}"]'
    backup: true
  become: true
- name: start and enable winlogbeat service
  win_service:
    name: winlogbeat
    start_mode: auto
    state: started
  become: true
