name: sudo user not in sudoers
type: frequency
index: filebeat-*

num_events: 1
timeframe:
  minutes: 5

filter:
- query:
    query_string: 
      query: '"user NOT in sudoers"'

alert:
- slack:
    slack_webhook_url: [slack_webhook]

alert_subject_args:
- "@timestamp"
- host.hostname
- host.os
- message
