---
- hosts: all
  tasks:
  - name: "create {{ username }} and add to {{ group }} group"
    win_user:
      name: "{{ username }}"
      password: "{{ password }}"
      state: present
    become: true
