---
- hosts: all
  tasks:
  - name: create {{ username }} and add to {{ group }} group
    user:
      name: "{{ username }}"
      uid: "{{ uid }}"
      append: yes
      password: "{{ password }}"
      groups: "{{ group }}"
      shell: /bin/bash
    become: true
