---
- name: pull postgres docker image
  docker_image:
    name: postgres
    tag: latest
    source: pull
  become: true
- name: create postgres volume
  docker_volume:
    name: "{{ postgres_name }}_volume"
  become: true
- name: run postgres container
  docker_container:
    name: "{{ postgres_name }}"
    image: postgres:latest
    restart_policy: unless-stopped
    volumes:
    - "{{ postgres_name }}_volume:/var/lib/postgresql/data"
    env:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
  become: true
