---
- hosts: all
  become: true
  vars:
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
    - name: docker
  tasks:
  - import_role: 
      name: geerlingguy.pip
    when: ansible_os_family != "Debian"
  - import_role: 
      name: geerlingguy.docker
    when: ansible_os_family != "Debian"
  roles:
  - { role: filebeat-install }
