version: '2'
services:
  joomla:
    image: joomla:JOOMLA_TAG
    links:
     - mysql
    ports:
     - "9092:80"
    environment:
     - JOOMLA_DB_HOST=mysql:3306
     - JOOMLA_DB_PASSWORD=JOOMLA_DB_PASSWORD
    volumes:
     - ./root_html:/var/www/html
    #log_driver: "syslog"
    #log_opt:
    #  syslog-address: "udp://SYSLOG_SERVER"
    #  syslog-tag: "joomla"

  mysql:
    image: mysql:latest
    command: ['--character-set-server=utf8','--default-authentication-plugin=mysql_native_password']
    environment:
     - MYSQL_USER=joomla
     - MYSQL_PASSWORD=JOOMLA_DB_PASSWORD
     - MYSQL_DATABASE=joomla
     - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
    ports:
     - 3306:3306
    expose:
     - "3306"
    volumes:
     - ./database:/var/lib/mysql
    #log_driver: "syslog"
    #log_opt:
    #  syslog-address: "udp://SYSLOG_SERVER"
    #  syslog-tag: "joomla_mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:PHPMYADMIN_TAG
    links:
     - mysql
    ports:
     - "9091:80"
    environment:
     - PMA_HOST=mysql
    #log_driver: "syslog"
    #log_opt:
      #syslog-address: "udp://SYSLOG_SERVER"
      #syslog-tag: "joomla_phpmyadmin"
