---
- name: git clone MozDef repository to /opt/mozdef
  git:
    repo: 'https://github.com/mozilla/MozDef.git'
    dest: /opt/mozdef
  become: true
- name: more secure permissions of /opt/mozdef
  file:
    path: /opt/mozdef
    mode: 0700
    owner: root
  become: true
- name: replace config in /opt/mozdef/meteor/imports/settings.js
  replace:
    path: /opt/mozdef/meteor/imports/settings.js
    regexp: 'rootURL: process.env.OPTIONS_METEOR_ROOTURL || "http://localhost",'
    replace: "rootURL: process.env.OPTIONS_METEOR_ROOTURL || \"http://{{ mozdef_uri }}\","
  become: true
- name: replace config in /opt/mozdef/meteor/imports/settings.js
  replace:
    path: /opt/mozdef/meteor/imports/settings.js
    regexp: 'port: process.env.OPTIONS_METEOR_PORT || "80",'
    replace: "port: process.env.OPTIONS_METEOR_PORT || \"{{ http_port }}\","
  become: true
- name: replace config in /opt/mozdef/meteor/imports/settings.js
  replace:
    path: /opt/mozdef/meteor/imports/settings.js
    regexp: 'kibanaURL: process.env.OPTIONS_METEOR_KIBANAURL || "http://localhost:9090/app/kibana",'
    replace: "kibanaURL: process.env.OPTIONS_METEOR_KIBANAURL || \"http://{{ mozdef_uri }}:9090/app/kibana\","
  become: true
- name: docker-compose build /opt/mozdef/docker/compose
  shell: "docker-compose build --build-arg ENV_FILE=/opt/mozdef/docker/compose/mozdef.env"
  args:
    chdir: /opt/mozdef/docker/compose
  become: true
- name: copy mozdef.service to /etc/systemd/system/mozdef.service
  copy:
    src: mozdef.service
    dest: /etc/systemd/system/mozdef.service
    owner: root
    mode: 0600
  become: true
- name: enable and start mozdef.service
  systemd:
    name: mozdef
    enabled: true
    state: started
  become: true
