---
- name: apt update && apt upgrade
  apt:
    update_cache: yes
    upgrade: dist
  become: true
- name: import proxmox key
  apt_key:
    url: http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg
    state: present
  become: true
- name: add proxmox installer repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve buster pve-no-subscription
    state: present
  become: true
- name: add proxmox ceph repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-nautilus buster main
    state: present
  become: true
- name: install proxmox
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - proxmox-ve
    - open-iscsi
  become: true
- name: reboot proxmox server
  reboot:
  become: true

