---
- name: add entry to hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{proxmox_ip}} {{ proxmox_hostname }}"
    insertafter: EOF
  become: true
- name: remove proxmox enterprise repo (if present)
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
  become: true
- name: apt update && apt upgrade
  apt:
    update_cache: yes
    upgrade: dist
  become: true
- name: import proxmox key
  apt_key:
    url: http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg
    state: present
  become: true
- name: add proxmox installer repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve buster pve-no-subscription
    state: present
  become: true
- name: add proxmox ceph repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-nautilus buster main
    state: present
  become: true
- name: install proxmox
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - pve-manager
    - proxmox-ve
    - open-iscsi
  become: true
- name: edit ssh config to allow root login
  command: sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
  become: true
- name: remove proxmox enterprise repo
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
  become: true
- name: reboot proxmox server
  reboot:
  become: true
