---
- name: create "{{ elk_system_user }}" system user
  user:
    name: "{{ elk_system_user }}"
    comment: 'elk docker system user'
    system: true
    uid: "{{ elk_system_user_uid }}"
  become: true
