---
- name: "create {{ container_name }} system user"
  user:
    name: "{{ container_name }}"
    comment: 'nginx docker system user'
    system: true
    uid: "{{ container_uid }}"
  become: true
- name: "create {{ container_name }} directory"
  file:
    path: "/opt/{{ container_name }}"
    mode: 0700
    owner: "{{ container_uid }}"
    state: directory
  become: true
- name: generate cert
  shell: "openssl req -x509 -newkey rsa:4096 -nodes -keyout /opt/{{ container_name }}/server.key -out /opt/{{ container_name }}/server.cert -days 365 -subj {{ self_sign_ssl_options }}"
  become: true
- name: copy nginx config 
  copy:
    src: nginx.conf
    dest: "/opt/{{ container_name }}/nginx.conf"
    owner: "{{ container_uid }}"
    mode: 0600
    backup: yes
    force: yes
  become: true
- name: begin nginx docker container
  docker_container:
    name: "{{ container_name }}_nginx"
    image: nginx
    restart_policy: unless-stopped
    ports:
    - "{{ ssl_port }}:{{ ssl_port }}" 
    volumes:
    - "/opt/{{ container_name }}/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "/opt/{{ container_name }}/server.key:/tmp/server.key:ro"
    - "/opt/{{ container_name }}/server.cert:/tmp/server.cert:ro"
  become: true
