---
- include_tasks: windows.yml
  when: ansible_facts['os_family'] == 'Windows'
- include_tasks: linux.yml
  when: ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Archlinux' or ansible_facts['os_family'] == 'Suse'
- include_tasks: darwin.yml
  when: ansible_facts['os_family'] == 'Darwin'
