---
- name: docker pull menzo/sn1per-docker
  docker_image:
    name: menzo/sn1per-docker
    source: pull
  become: true
- name: run sn1per
  shell: "docker run --rm -ti -v /tmp/sniper:/usr/share/sniper/loot/ menzo/sn1per-docker sniper -t {{ target_net }}"
  become: true 
