---
- name: docker pull menzo/sn1per-docker
  docker_image:
    name: menzo/sn1per-docker
    source: pull
  become: true
- name: run sn1per
  shell: "docker exec --rm -v /tmp/sniper:/tmp/ menzo/sn1per-docker sniper -t {{ target_net }} >> /tmp/{{ target_net }}-$(date +%M-%d-%Y_%H:%S).txt"
  become: true 
